In [34]:
from sklearn.feature_selection import SelectFromModel
import pandas as pd
from sklearn import preprocessing
from sklearn.linear_model import Lasso, LinearRegression
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
df = pd.read_csv('dataset/data_merged.csv')

In [3]:
df.head()

acousticness  danceability  duration_ms  energy  explicit  \
0        0.0131        0.2560       182347   0.895         0   
1        0.9800        0.2770       206972   0.145         0   
2        0.7950        0.6850       314667   0.483         0   
3        0.6560        0.7880       179747   0.808         0   
4        0.3020        0.0753       498560   0.150         0   

   instrumentalness  liveness  loudness  popularity  speechiness  ...  \
0          0.000106    0.0821    -4.860          29       0.0707  ...   
1          0.879000    0.1110   -19.898           0       0.0845  ...   
2          0.878000    0.1130   -10.202           1       0.0337  ...   
3          0.000000    0.1540    -6.590           0       0.0395  ...   
4          0.884000    0.1210   -16.705           0       0.0371  ...   

   valence_yr  popularity_yr  mode  key_0_yr  key_1_yr  key_2_yr  key_3_yr  \
0    0.583424      35.272231     1         0         0         1         0   
1    0.432251       3.672500     1         1         0         0         0   
2    0.447291       7.707000     1         0         0         0         1   
3    0.447291       7.707000     1         0         0         0         1   
4    0.443625       3.419500     1         1         0         0         0   

   key_4_yr  key_5_yr  key_6_yr  
0         0         0         0  
1         0         0         0  
2         0         0         0  
3         0         0         0  
4         0         0         0  

[5 rows x 72 columns]

In [8]:
scaler = preprocessing.StandardScaler().fit(df.drop(['popularity'], axis=1))
columns = df.drop(['popularity'], axis=1).columns
X = pd.DataFrame(scaler.transform(df.drop(['popularity'], axis=1)), columns=columns)
y = df['popularity']

In [9]:
X.head()

acousticness  danceability  duration_ms    energy  explicit  \
0     -1.288412     -1.593592    -0.341936  1.521922 -0.270019   
1      1.260133     -1.474178    -0.174619 -1.235111 -0.270019   
2      0.772512      0.845876     0.557122  0.007392 -0.270019   
3      0.406137      1.431576    -0.359601  1.202107 -0.270019   
4     -0.526932     -2.621126     1.806596 -1.216731 -0.270019   

   instrumentalness  liveness  loudness  speechiness     tempo  ...  \
0         -0.585218 -0.715682  1.215760    -0.192274  2.455180  ...   
1          2.054319 -0.555713 -1.427082    -0.116886 -1.363247  ...   
2          2.051316 -0.544643  0.276934    -0.394401 -0.635302  ...   
3         -0.585536 -0.317698  0.911722    -0.362717 -0.128480  ...   
4          2.069335 -0.500361 -0.865930    -0.375828 -1.333072  ...   

   valence_yr  popularity_yr  mode  key_0_yr  key_1_yr  key_2_yr  key_3_yr  \
0    1.045259       0.628191   0.0 -0.758339 -0.250076  3.062932 -0.234826   
1   -1.671851      -1.448124   0.0  1.318672 -0.250076 -0.326485 -0.234826   
2   -1.401527      -1.183031   0.0 -0.758339 -0.250076 -0.326485  4.258467   
3   -1.401527      -1.183031   0.0 -0.758339 -0.250076 -0.326485  4.258467   
4   -1.467413      -1.464748   0.0  1.318672 -0.250076 -0.326485 -0.234826   

   key_4_yr  key_5_yr  key_6_yr  
0 -0.700788 -0.318773 -0.076689  
1 -0.700788 -0.318773 -0.076689  
2 -0.700788 -0.318773 -0.076689  
3 -0.700788 -0.318773 -0.076689  
4 -0.700788 -0.318773 -0.076689  

[5 rows x 71 columns]

In [11]:
selector = SelectFromModel(estimator=Lasso()).fit(X, y)
selector.estimator_.coef_

array([-0.        ,  0.        , -0.        ,  0.        ,  0.        ,
       -0.        , -0.        ,  0.        , -0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        , -0.        ,
       -0.        ,  0.        , -0.        ,  0.        , -0.        ,
        0.        , -0.        , -0.        ,  0.        ,  0.        ,
       -0.        , -0.        ,  0.        , -0.        ,  0.        ,
       -0.        , -0.        ,  0.        ,  0.        ,  0.        ,
        0.        , 17.41041716, -0.        , -0.        , -0.        ,
       -0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
       -0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
       -0.        , -0.        , -0.        ,  0.        ,  0.        ,
        0.        , -0.        ,  0.        ,  0.        , -0.        ,
        0.        ,  0.        ,  1.94200037,  0.        , -0.        ,
        0.        ,  0.        , -0.        ,  0.        ,  0.  

In [12]:
selector.transform(X)

array([[ 0.51803935,  0.62819112],
       [-1.20659199, -1.4481245 ],
       [-1.01175205, -1.18303061],
       ...,
       [ 0.01543759, -0.42579316],
       [ 0.04263247,  0.53954012],
       [ 0.60489253,  0.53954012]])

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [21]:
regf = LinearRegression()
scores = cross_val_score(regf, X_train, y_train, cv=5)
scores

array([0.83217757, 0.83074118, 0.82904008, 0.82741932, 0.83451041])

In [28]:
regf.fit(X_train,y_train)
y_pred = regf.predict(X_test)
type(y_pred)

numpy.ndarray

In [33]:
mean_squared_error(y_test, y_pred)

81.21832522490942

In [35]:
r2_score(y_test, y_pred)

0.8308637215164697